"""initial schema

Revision ID: aabb61820ddb
Revises: 
Create Date: 2026-08-18 20:56:50.335143

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aabb61820ddb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Requis pour server_default=gen_random_uuid() sur toutes les tables
    # ci-dessous (section 6.1 : "id" UUID par défaut côté serveur).
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('retention_policy_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entitlements',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('product_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'source', 'product_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('local_created_at', sa.DateTime(), nullable=False),
    sa.Column('server_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('carrier_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_ref', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_organization_id', 'incidents', ['organization_id'], unique=False)
    op.create_index('ix_incidents_organization_status', 'incidents', ['organization_id', 'status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('metadata_safe_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_incident_id', 'audit_events', ['incident_id'], unique=False)
    op.create_index('ix_audit_events_organization_id', 'audit_events', ['organization_id'], unique=False)
    op.create_table('delivery_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('ocr_status', sa.String(length=30), nullable=False),
    sa.Column('extracted_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_documents_incident_id', 'delivery_documents', ['incident_id'], unique=False)
    op.create_table('export_bundles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pdf_object_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'version', name='uq_export_bundles_incident_version')
    )
    op.create_index('ix_export_bundles_incident_id', 'export_bundles', ['incident_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issues_incident_id', 'issues', ['incident_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('rule_pack_id', sa.String(length=100), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_incident_id', 'reminders', ['incident_id'], unique=False)
    op.create_table('reserve_texts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('template_version', sa.String(length=30), nullable=False),
    sa.Column('confirmed_fact_revision', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reserve_texts_incident_id', 'reserve_texts', ['incident_id'], unique=False)
    op.create_table('candidate_fact_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('raw_structured_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_fact_sets_issue_id', 'candidate_fact_sets', ['issue_id'], unique=False)
    op.create_table('confirmed_fact_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=60), nullable=False),
    sa.Column('confirmed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'revision', name='uq_confirmed_fact_sets_issue_revision')
    )
    op.create_index('ix_confirmed_fact_sets_issue_id', 'confirmed_fact_sets', ['issue_id'], unique=False)
    op.create_table('evidence_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('original_object_key', sa.String(length=500), nullable=False),
    sa.Column('preview_object_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('captured_at_device', sa.DateTime(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_object_key', name='uq_evidence_assets_original_key')
    )
    op.create_index('ix_evidence_assets_incident_id', 'evidence_assets', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_assets_incident_id', table_name='evidence_assets')
    op.drop_table('evidence_assets')
    op.drop_index('ix_confirmed_fact_sets_issue_id', table_name='confirmed_fact_sets')
    op.drop_table('confirmed_fact_sets')
    op.drop_index('ix_candidate_fact_sets_issue_id', table_name='candidate_fact_sets')
    op.drop_table('candidate_fact_sets')
    op.drop_index('ix_reserve_texts_incident_id', table_name='reserve_texts')
    op.drop_table('reserve_texts')
    op.drop_index('ix_reminders_incident_id', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_issues_incident_id', table_name='issues')
    op.drop_table('issues')
    op.drop_index('ix_export_bundles_incident_id', table_name='export_bundles')
    op.drop_table('export_bundles')
    op.drop_index('ix_delivery_documents_incident_id', table_name='delivery_documents')
    op.drop_table('delivery_documents')
    op.drop_index('ix_audit_events_organization_id', table_name='audit_events')
    op.drop_index('ix_audit_events_incident_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_incidents_organization_status', table_name='incidents')
    op.drop_index('ix_incidents_organization_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_users_organization_id', table_name='users')
    op.drop_table('users')
    op.drop_table('entitlements')
    op.drop_table('organizations')
    # ### end Alembic commands ###
